cask_args appdir: '/Applications'

tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "puma/puma"

brew "autoconf"
brew "automake"
brew "docker-completion"
brew "docker-compose-completion"
brew "coreutils"
brew "curl"
brew "dnote"
brew "dos2unix"
brew "git"
brew "git-lfs"
brew "inetutils"
brew "libtool"
brew "graphicsmagick"
brew "imagemagick"
brew "jmeter"
brew "libksba"
brew "libyaml"
brew "openssl@1.1"
brew "pkg-config"
brew "readline"
brew "spark"
brew "tmux"
brew "watch"
brew "watchman"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"

unless ENV['HOMEBREW_SYSTEM'] == 'Linux'
  brew "gcc"
  brew "mas"
  brew "putty"
  brew "tesseract", args: ["with-all-languages"]

  cask "font-hack-nerd-font"
  cask "postman"
  cask "visual-studio-code"
  cask "caskroom/fonts/font-fira-code"
  cask "azure-data-studio"
end
